### ISSUE TITLE
Download profiles via dvc command line 

### ISSUE THREAD

**Issue by benoalo** [broadinstitute/lincs-cell-painting#71]
Hi @gwaygenomics and team,

We've worked on some cell profiling tools and would be interested to try them on this dataset. Unfortunately I am having trouble to download the profile data. It would be great if you would have pointers to help with that?
 
At the moment I tried the dvc get command line tools (I am new to it but quite excited by the concept 😊) but I probably do something wrong (I tried this on windows10 from a powershell terminal) 

![Capture](https://user-images.githubusercontent.com/7521101/123433905-368a2580-d5cc-11eb-889c-841430c96dcf.PNG)

Thanks for your help,

Kind regards,
Benoit

**Comment by gwaygenomics** [comment]
Hi @benoalo - thanks for your interest in this repo!

I've tried that command on my local machine and it works just fine. I did a bit of sleuthing, and it looks like the issue might have to do with your AWS credentials. Maybe this is helpful: https://github.com/iterative/dvc/issues/3050#issuecomment-674340656

The AWS bucket is publicly available, so you should be able to download no problem. If you have any additional followup questions, or if you find the solution, please do let us know!

**Comment by benoalo** [comment]
Hi @gwaygenomics ,

Thank you for the pointer, my default AWS credential profile was the culprit and changing it solved the issue.

Initially I didn't realized the link with AWS. Checking the remote location was useful to troubleshoot (i.e. with `dvc remote list` command in the git repo). Then with aws cli it was easy to find which credentials worked fine :-) .

**Comment by gwaygenomics** [comment]
Great! Thanks for following up confirming the solution. Let us know if you have any other questions.

**Comment by FloHu** [comment]
Hi @gwaygenomics , 
I have been less successful it seems. I get the following error:

![image](https://user-images.githubusercontent.com/9386875/124138417-ebb65500-da86-11eb-860b-9f73f2ed1cb9.png)

I thought it is because the add-jump-cp-role only allows access to the jump-cellpainting prefix. I have been able to download data from s3://jump-cellpainting
But @shntnu said it should be publicly accessible.

@benoalo may I ask what aws cli tools you used to track down the issue?

**Comment by gwaygenomics** [comment]
Hi @FloHu - I believe you are looking for [`aws configure`](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html). Once you provide credentials, `dvc pull` should just work.

**Comment by FloHu** [comment]
Hi @gwaygenomics - I did run `aws configure` following all instructions from our [aws repository](https://github.com/jump-cellpainting/aws). I am able to download images from the s3://jump-cellpainting bucket as well. But then any operation on s3://cellpainting-datasets fails, I do not even have permission for `aws s3 ls`.

**Comment by FloHu** [comment]
OK it works now: the problem was that I assumed the jumpcprole (see also [here](https://github.com/jump-cellpainting/aws)) by default, which I had set up in order to access consortium data. Apparently though this role is less privileged than any normal user when it comes to accessing any s3 bucket _outside of_ s3://jump-cellpainting. Running `aws-sso` to get a new access token for any user and then using this user profile solved the issue.

**Comment by gwaygenomics** [comment]
awesome, glad this is resolved. And thanks for posting here, I think others might run into this same issue, so thanks for solving for all!
